### PR TITLE
Add ChromatiCraft support, TC magic forest bigger

### PR DESCRIPTION
**Pull request by Dream-Master**
re-open this pr

https://github.com/GTNewHorizons/Realistic-World-Gen/pull/5

### CODE REVIEW

**Comment by Dream-Master** [comment]
@KuroPeach i just reopen the pr .

**Comment by KuroPeach** [comment]
I used dapi to generate two pictures. This is the comparison of the size of the magic forest after the rwg change. They use the same seeds. The bright green is the magic forest, and the purple is the place of corruption.

before change
-3, 4  (10001x10001;  R=10 b-px, G=-1-false )

after change
4, -1  (10001x10001;  R=10 b-px, G=-1-false )

**Comment by Dream-Master** [comment]
@KuroPeach did you test in a GTNH full pack ? (2.3.0)

**Comment by Dream-Master** [comment]
now the forrest are very huge

**Comment by KuroPeach** [comment]
I can add bop, the last test only has rwg biome and tc biome, so it is very big

**Comment by Dream-Master** [comment]
run it in a gtnh 2.3.0 instance

**Comment by KuroPeach** [comment]
In the case of the full package test, my notebook does not start fast enough. If bop is involved, the test results are not much different from the full package. ：）
before change
304, -4  (10001x10001;  R=10 b-px, G=-1-false )
after change It seems that only the upper left is the magic forest, there are too many bop biomes
298, -2  (10001x10001;  R=10 b-px, G=-1-false )

**Comment by Dream-Master** [comment]
yea but we dont use bop worldgen. We use rwg put bop content to rwg world gen

**Comment by KuroPeach** [comment]
Yes, this test also uses the rwg generator，Because bop's generator is not a regular polygon, only rwg will generate such a pattern ：）

**Comment by Dream-Master** [comment]
so what color the magical forest has ?

**Comment by KuroPeach** [comment]
still is bright green
!legend

**Comment by Dream-Master** [comment]
ok need to check ingame later

**Comment by Alastors** [comment]
I’m all for it, certain parts of thaumcraft are hidden in the forest and they’re borderline impossible to find, and even when you do they’re only like a chunk total size so effectively useless as currently is.

And I mean it shouldn’t have too much of an effect on existing worlds, I mean it’ll probably cause some sort of jagged chunk borders between the old chunks and new chunks, but honestly that’s not enough of a reason to not do it.

**Comment by Dream-Master** [comment]
@KuroPeach sorry this take some time. We are willing to test this pr in gtnh can you add this change to a config so we can change values there ? Thanks

**Review by mitchej123 — CHANGES_REQUESTED** [review]
Needs to be behind a config.  It should default to off for existing worlds, but being on for new worlds is fine
   I don't want to introduce jagged borders to people that have an existing world unless they opt into it


Other than that seems fine.

**Comment by KuroPeach** [comment]
> @KuroPeach sorry this take some time. We are willing to test this pr in gtnh can you add this change to a config so we can change values there ? Thanks

Sorry, I can't add a configuration file to it. I don't know how to code, I just make the existing modifications, and the original author didn't provide a configuration file to modify the parameters.

**Comment by Dream-Master** [comment]
Where is the original author so I can contact him or her @KuroPeach ?

**Comment by KuroPeach** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1281910-teds-world-gen-mods-realistic-world-gen-alpha-1-3
Unable to contact, he or she appears to have been out of the community for 8 years

**Comment by Dream-Master** [comment]
in this case i see no chance for the pr to be added.

**Pull request closed without merging**
