### PR TITLE
add support for abyssalcraft and ars magica 2.5 biomes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Dream-Master** [comment]
?
this pr change only spaces so it does nothing by itself

**Comment by Dream-Master** [comment]
image

**Comment by vovaksenov** [comment]
I saw @bessonowjaroslaw on discord asking how to use github, so my guess is, he added wrong changes into the pull request.

**Comment by Dream-Master** [comment]
> I saw @bessonowjaroslaw on discord asking how to use github, so my guess is, he added wrong changes into the pull request.

That might be true but if you are new to git you just need to ask someone for help first before you try random stuff.

**Comment by Dream-Master** [comment]
@bessonowjaroslaw so try again please

**Pull request closed without merging**
