### PR TITLE
Add ChromatiCraft support, TC magic forest bigger

### PR DESCRIPTION
**Pull request by KuroPeach**
Add ChromatiCraft support, TC magic forest bigger，But the code needs to be optimized

### CODE REVIEW

**Comment by Dream-Master** [comment]
@KuroPeach can you show how much bigger magical forest is with this change ?

**Comment by KuroPeach** [comment]
Now its size is similar to forest and taiga, instead of the default small clump, or even the size of a block
image

**Comment by Dream-Master** [comment]
@KuroPeach did it break existing worlds generated with RWG ?

**Comment by KuroPeach** [comment]
No, it is the method that comes with rwg, refer to bop biome, and tc biome detection method

**Comment by Dream-Master** [comment]
oh i did a mistake

**Pull request merged**
